# Generated by Django 5.0.6 on 2024-07-28 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_product_is_sale_product_sale_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(blank=True, default='upload/product/—Pngtree—a picture icon_4524748.png', null=True, upload_to='upload/product/'),
        ),
        migrations.DeleteModel(
            name='Order',
        ),
    ]
