# Generated by Django 5.0.6 on 2024-08-02 02:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_rename_user_userprofile_avatar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='avatar',
            name='imagen',
            field=models.ImageField(blank=True, default='avatares/Login_default_Avatar.png', null=True, upload_to='avatares'),
        ),
    ]
