# Generated by Django 5.0.6 on 2024-06-21 04:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppCoder', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='estudiante',
            name='curso',
            field=models.CharField(default='', max_length=30),
            preserve_default=False,
        ),
    ]
